### ISSUE TITLE
fetch_setting: undefined method [] for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Pshellvon** [lagartoflojo/sensu-plugins-telegram#9]
Hello!

Plugin does not work...

Sensu version 1.5.0-1

```
"/usr/local/bundle/gems/sensu-plugins-telegram-2.0.1/bin/handler-telegram.rb:68:in `fetch_setting': undefined method `[]' for nil:NilClass (NoMethodError)
from /usr/local/bundle/gems/sensu-plugins-telegram-2.0.1/bin/handler-telegram.rb:114:in `build_message'
from /usr/local/bundle/gems/sensu-plugins-telegram-2.0.1/bin/handler-telegram.rb:140:in `params'
from /usr/local/bundle/gems/sensu-plugins-telegram-2.0.1/bin/handler-telegram.rb:159:in `handle'
from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-handler.rb:99:in `block in <class:Handler>'
warning: event filtering in sensu-plugin is deprecated, see http://bit.ly/sensu-plugin
warning: occurrence filtering in sensu-plugin is deprecated, see http://bit.ly/sensu-plugin"
```

**Comment by lagartoflojo** [comment]
I was able to replicate your error by configuring the handler incorrectly.
Make sure you have something like this, for example in `/etc/sensu/conf.d/handlers/telegram.json`


```json
{
  "handlers": {
    "telegram": {
      "type": "pipe",
      "command": "handler-telegram.rb"
    }
  },
  "telegram": {
    "bot_token": "YOUR_BOT_TOKEN",
    "chat_id": -123123
  }
}
```

After fixing this file, remember to restart Sensu:

```
sudo systemctl restart sensu-{server,api}
```

You can double-check that Sensu loaded your config correctly by querying sensu-api:

```
curl -s http://sensu-api-server-url:4567/settings
```



I replicated your error by removing the top-level `telegram` object, and keeping only the `handlers` one:


**THIS IS WRONG:**

```json
{
  "handlers": {
    "telegram": {
      "type": "pipe",
      "command": "handler-telegram.rb"
    }
  }
}
```
